### LSE Data Analytics Online Career Accelerator

# DA201: Data Analytics using Python

## Practical activity: Create a DataFrame from the dictionary

**This is the start to the activity.**

A peer has come to you for help. They have started building a dictionary using Jupyter Notebook. Below you will find their incomplete code. Now that you have learned to add values and keys using a DataFrame, make changes to the code to complete the following:
- Import the dictionary into a DataFrame and add two more rows to the state and capital columns.
- Sense-check the code that was presented to you is accurate and free from errors.

### Raw data
- states = ["Acre", "Alogoas", "Amapa", "Amazonas", "Bahia", "Ceara", "Distrito Federal", 
            "Espirito Santo", "Goiás", "Maranhao", "Mato grosso", "Mato grosso do sul", 
            "Minas gerais", "Para", "Paraiba", "Parana", "Pernambuco", "Piaui", "Rio de Janeiro", 
            "Rio Grande do norte", "Rio Grande do Sul", "Rondonia", "Roraima", "Santa Catarina", 
            "Sao Paulo", "Sergipe", "Tocantins"]

- capitals = ["Rio Branco", "Maceió" "Macapá", "Manaus", "Salvador", "Fortaleza", "Brasília", 
              "Vitória", "Goiânia", "São Luís", "Cuiabá", "Campo Grande","Belo Horizonte","Belém",
              "João Pessoa", "Curitiba", "Recife", "Teresina", "Rio de Janeiro", "Natal", "Porto Alegre", 
              "Porto Velho", "Boa Vista", "Florianópolis", "São Paulo", "Aracaju", "Palmas"]

### Incomplete Dictionary

In [4]:
import pandas as pd
import numpy as np

In [5]:
Brazil = {'states': ['Acre', 'Alogoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara', 'Distrito Federal', 'Espirito Santo',
                      'Goias', 'Maranhao', 'Mato grosso', 'Mato grosso do sul', 'Minas gerais', 'Para', 'Paraiba',
                      'Parana', 'Perambuco', 'Piaui', 'Rio de Janeiro', 'Rio Grande de Norto', 'Rio grande do dul',
                      'Rondonia', 'Roraima', 'Santa Catarina', 'Sao Paulo', 'Sergipe', 'Tocatins'],
         'Capitals': ['Rio Branco', 'Maceio', 'Macapa', 'Manaus', 'Salvador', 'Fortaleza', 'Brasilia', 'Vitoria',
                       'Gioania', 'Sao Luis', 'Cuiaba', 'Campo Grande', 'Belo horizonte', 'belem', 'Joao Pessoa',
                       'Curitiba', 'Recife', 'Teresina', 'Rio de Janieiro', 'Natal', 'Porto Alegre', 'Porto Velho',
                       'Boa Vista', 'Florianopolis', 'Sao Paulo', 'Aracaju', 'Palmas']}
    
Brasil1 = pd.DataFrame(Brazil)
Brasil1

                 states         Capitals
0                  Acre       Rio Branco
1               Alogoas           Maceio
2                 Amapa           Macapa
3              Amazonas           Manaus
4                 Bahia         Salvador
5                 Ceara        Fortaleza
6      Distrito Federal         Brasilia
7        Espirito Santo          Vitoria
8                 Goias          Gioania
9              Maranhao         Sao Luis
10          Mato grosso           Cuiaba
11   Mato grosso do sul     Campo Grande
12         Minas gerais   Belo horizonte
13                 Para            belem
14              Paraiba      Joao Pessoa
15               Parana         Curitiba
16            Perambuco           Recife
17                Piaui         Teresina
18       Rio de Janeiro  Rio de Janieiro
19  Rio Grande de Norto            Natal
20    Rio grande do dul     Porto Alegre
21             Rondonia      Porto Velho
22              Roraima        Boa Vista
23       Santa Catarina    Florianopolis
24            Sao Paulo        Sao Paulo
25              Sergipe          Aracaju
26             Tocatins           Palmas

In [7]:
Brazil1 = {'states': ['state_1', 'state_2'], 'Capitals': ['capital_1', 'capital_2']}
brasil2 = pd.DataFrame(Brazil1)
brasil2

    states   Capitals
0  state_1  capital_1
1  state_2  capital_2

In [8]:
Brazil_fires = pd.concat([Brasil1, brasil2], ignore_index=True)
Brazil_fires

                 states         Capitals
0                  Acre       Rio Branco
1               Alogoas           Maceio
2                 Amapa           Macapa
3              Amazonas           Manaus
4                 Bahia         Salvador
5                 Ceara        Fortaleza
6      Distrito Federal         Brasilia
7        Espirito Santo          Vitoria
8                 Goias          Gioania
9              Maranhao         Sao Luis
10          Mato grosso           Cuiaba
11   Mato grosso do sul     Campo Grande
12         Minas gerais   Belo horizonte
13                 Para            belem
14              Paraiba      Joao Pessoa
15               Parana         Curitiba
16            Perambuco           Recife
17                Piaui         Teresina
18       Rio de Janeiro  Rio de Janieiro
19  Rio Grande de Norto            Natal
20    Rio grande do dul     Porto Alegre
21             Rondonia      Porto Velho
22              Roraima        Boa Vista
23       Santa Catarina    Florianopolis
24            Sao Paulo        Sao Paulo
25              Sergipe          Aracaju
26             Tocatins           Palmas
27              state_1        capital_1
28              state_2        capital_2

In [9]:
Brazil_fires = Brasil1.append(brasil2, ignore_index=True)
Brazil_fires

C:\Users\srini\AppData\Local\Temp\ipykernel_26412\2876712301.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Brazil_fires = Brasil1.append(brasil2, ignore_index=True)

                 states         Capitals
0                  Acre       Rio Branco
1               Alogoas           Maceio
2                 Amapa           Macapa
3              Amazonas           Manaus
4                 Bahia         Salvador
5                 Ceara        Fortaleza
6      Distrito Federal         Brasilia
7        Espirito Santo          Vitoria
8                 Goias          Gioania
9              Maranhao         Sao Luis
10          Mato grosso           Cuiaba
11   Mato grosso do sul     Campo Grande
12         Minas gerais   Belo horizonte
13                 Para            belem
14              Paraiba      Joao Pessoa
15               Parana         Curitiba
16            Perambuco           Recife
17                Piaui         Teresina
18       Rio de Janeiro  Rio de Janieiro
19  Rio Grande de Norto            Natal
20    Rio grande do dul     Porto Alegre
21             Rondonia      Porto Velho
22              Roraima        Boa Vista
23       Santa Catarina    Florianopolis
24            Sao Paulo        Sao Paulo
25              Sergipe          Aracaju
26             Tocatins           Palmas
27              state_1        capital_1
28              state_2        capital_2

In [10]:
print(Brazil_fires.shape)

(29, 2)